name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  style:
    name: Check style conventions
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Setup the checking tools
        run: |
          python -m venv env
          source env/bin/activate
          $HOME/.poetry/bin/poetry install
      - name: Test the package style conventions
        run: |
          source env/bin/activate
          make check
